apiVersion: v1
kind: Service
metadata:
  name: infinispan-discovery-service
  labels:
    app: infinispan
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: infinispan
  ports:
    - protocol: TCP
      port: 7800
      targetPort: 7800
