apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infinispan-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      serviceAccountName: backendpoc
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        runAsUser: 0
      containers:
        - name: application
          securityContext: {}
          image: infinispan-embedded
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7800
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Dcache.type=cluster -Djgroups.dns.query=infinispan-discovery-service.default.svc.cluster.local -Djgroups.bind.address=SITE_LOCAL -Djava.net.preferIPv4Stack=false -Dhibernate.cache.infinispan.jgroups_cfg=default-configs/default-jgroups-kubernetes.xml"
